<a href="https://colab.research.google.com/github/HVBLEGENDZZ9/COLAB-SNIPPETS/blob/main/Basics__of_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

INTRODUCTION TO TENSORFLOW:


*   Introduction to tensors
*   Getting information from tensors
*   Manipulating tensors
*   Tensors and Numpy
*   Using @tf.function(a way to speed up your regular python functions)
*   Using GPUs with Tensorflow(or TPUs)



# **-Introduction to tensors**

In [1]:
import tensorflow as tf
print(tf.__version__)

2.6.0


In [2]:
#creating tensors
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#check the number of dimensions of the tensor
scalar.ndim

0

In [4]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
#checking the dimensions of the vector
vector.ndim

1

In [6]:
#create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
#checking the dimensions of the matrix
matrix.ndim

2

In [8]:
matrix2 = tf.constant([[10,7],[7,10]],dtype=tf.float16)

In [9]:
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

## **Creating tensors with tf.Variable**

In [10]:
#createing tensor using tf.variable
changeable_tensor = tf.Variable([9,1])
unchangeable_tensor = tf.constant([69,420])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 1], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 69, 420], dtype=int32)>)

In [11]:
#changing the value in tf.variable
changeable_tensor[1].assign(3)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 3], dtype=int32)>

In [12]:
#we cannot change the values in a constant tensor
unchangeable_tensor[1].assign(4)

AttributeError: ignored

NOTE:IN MOST OF THE CASES, TENSORFLFOW WILL AUTOMATICALLY DECIDE BETWEEN tf.constant AND tf.variable. BUT IF GIVEN A CHOICE, USUALLY GO FOR tf.constant

## **Creating random tensors with tf.random**

In [13]:
random_tensor1 = tf.random.Generator.from_seed(42)
random_tensor1 = random_tensor1.normal(shape = (3,2))
random_tensor2 = tf.random.Generator.from_seed(42)
random_tensor2 = random_tensor2.normal(shape = (3,2))
random_tensor1,random_tensor2
#we can see that although it is called random, specifying the seed actually creates the same tensors

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>)

In [14]:
#if we change the seed
random_tensor2 = tf.random.Generator.from_seed(69)
random_tensor2 = random_tensor2.normal(shape=(3,2))
random_tensor1,random_tensor2,random_tensor1 == random_tensor2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.29164317,  1.4531525 ],
        [-0.8223833 , -1.3446565 ],
        [-0.7183838 , -0.20373917]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

### **Shuffling the order of tensors so that we get a more homogenous non partial dataset**

In [15]:
tf.random.Generator.from_seed(42)#global seed
non_shuffled = tf.constant([[69,420],[9,9],[3,2]])
tf.random.shuffle(non_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[  3,   2],
       [  9,   9],
       [ 69, 420]], dtype=int32)>

In [16]:
non_shuffled = tf.constant([[69,420],[9,9],[3,2]])
non_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 69, 420],
       [  9,   9],
       [  3,   2]], dtype=int32)>

### **Other ways to make tensors**

In [17]:
#using numpy
import numpy as np
numpy_arr = np.array([[1,2],[3,4]])
numpy_arr

array([[1, 2],
       [3, 4]])

In [18]:
numpy_arr1 = np.ones((2,2))
numpy_arr1

array([[1., 1.],
       [1., 1.]])

In [19]:
numpy_arr0 = np.zeros(shape = (2,2))
numpy_arr0

array([[0., 0.],
       [0., 0.]])

In [20]:
tensor = tf.constant(numpy_arr)
tensor

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4]])>

In [21]:
tensor = tf.zeros(shape = (3,2))
tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [22]:
#reshaping the arrays
tensor = tf.constant(numpy_arr0,shape=(1,4))
tensor

<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[0., 0., 0., 0.]])>

### **Getting information from our tensors**

*  rank means the number of dimensions
*  shape means the shape of our tensor
*  axis means the dimension along whcih we want our data
*  size means the total number of elements in our tensor

In [23]:
#creating a tensor of rank 4(4 dimensions)
tensor_rank4 = tf.zeros(shape=[2,3,4,5])
tensor_rank4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [24]:
tensor_rank4[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [25]:
print("THE RANK OF THE TENSOR IS: ",tensor_rank4.ndim) 
print("THE SHAPE OF THE TENSOR IS: ",tf.shape(tensor_rank4).numpy()) 
print("THE SIZE OF THE TENSOR IS: ",tf.size(tensor_rank4).numpy()) 
print("THE ELEMENTS ALONG THE FIRST AXIS ARE: ",tensor_rank4.shape[0]) 
print("THE ELEMENTS ALONG THE LAST AXIS ARE: ",tensor_rank4.shape[-1])

THE RANK OF THE TENSOR IS:  4
THE SHAPE OF THE TENSOR IS:  [2 3 4 5]
THE SIZE OF THE TENSOR IS:  120
THE ELEMENTS ALONG THE FIRST AXIS ARE:  2
THE ELEMENTS ALONG THE LAST AXIS ARE:  5


### **Indexing out tensors**

In [26]:
#getting the first 2 elements from each dimension of our rank 4 tensor
tensor_rank4[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [27]:
#getting the first element of each dimension in our tensor
tensor_rank4[:1,:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

### **Expanding the dimensions of our tensors**

In [28]:
tensor_rank2 = tf.constant([[9,1],[69,420]])
tensor_rank2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  9,   1],
       [ 69, 420]], dtype=int32)>

In [29]:
tensor_rank3 = tensor_rank2[...,tf.newaxis]
tensor_rank3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[  9],
        [  1]],

       [[ 69],
        [420]]], dtype=int32)>

In [30]:
#other alternative
tensor_rank3 = tf.expand_dims(tensor_rank2,axis = -1)
tensor_rank3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[  9],
        [  1]],

       [[ 69],
        [420]]], dtype=int32)>

In [31]:
tensor_rank3 = tf.expand_dims(tensor_rank2,axis = 1)
tensor_rank3

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[  9,   1]],

       [[ 69, 420]]], dtype=int32)>

### **Manipulating tensors using basic operations**

In [32]:
tensor_rank2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  9,   1],
       [ 69, 420]], dtype=int32)>

In [33]:
tensor_rank2 = tensor_rank2 + 10
tensor_rank2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 19,  11],
       [ 79, 430]], dtype=int32)>

In [34]:
tensor_rank2 = tensor_rank2/10
tensor_rank2
#same with substracrtion and division
#all the above operations are element-wise operations

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 1.9,  1.1],
       [ 7.9, 43. ]])>

### **Matrix multiplication in tensorflow**

In [35]:
tensor_rank2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 1.9,  1.1],
       [ 7.9, 43. ]])>

In [36]:
multimat = tf.matmul(tensor_rank2,tensor_rank2)
multimat
#rules of matrix multiplication have to be followed

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[  12.3 ,   49.39],
       [ 354.71, 1857.69]])>

In [37]:
tensor_rank2 @ tensor_rank2 #python symbol for matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[  12.3 ,   49.39],
       [ 354.71, 1857.69]])>

In [38]:
mat1 = tf.constant([[1,2],[3,4],[5,6]])
mat1


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [39]:
mat2 = tf.constant([[7,8],[9,10],[11,12]])
mat2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [41]:
mat1 @ mat2

InvalidArgumentError: ignored

In [42]:
#to fix the above error
mat1 @ tf.transpose(mat2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [43]:
#another way to fix the above error
mat1 @ tf.reshape(mat2,shape = (2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [44]:
tf.reshape(mat2,shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [45]:
tf.transpose(mat2)
#generally we will be using transpose instead of reshape to multiply 

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]], dtype=int32)>

### **Changing the data type of the tensors**

In [46]:
#default is 32 bit precision
A = tf.constant([1,2,3,4])
A.dtype

tf.int32

In [47]:
B = tf.constant([5.,6.,7.,8.])
B.dtype

tf.float32

In [48]:
#channgind dtype
B = tf.cast(B,dtype = tf.float16)
B.dtype
#16 bit precision reduces the size of the tensor in the memory and also works very fast
#due to hardware acceleration

tf.float16

### **Aggregating tensors**

In [49]:
#aggregation means to scale down from a lot of values to a less number of values
tensor = tf.constant(np.random.randint(1,100,50))
tensor = tf.cast(tensor,dtype = tf.float32)

In [50]:
#finding max, min, mean, sum, std, variance
print("THE MAX ELEMENT IS: ",tf.reduce_max(tensor).numpy())
print("THE MIN ELEMENT IS: ",tf.reduce_min(tensor).numpy())
print("THE SUM OF THE ELEMENTS IS: ",tf.reduce_sum(tensor).numpy())
print("THE MEAN OF ALL THE ELEMENTS IS: ",tf.reduce_mean(tensor).numpy())
print("THE STANDARD DEVIATION OF ALL THE ELEMENTS IS: ",tf.math.reduce_std(tensor))
import tensorflow_probability as tfp
print("THE VARIANCE OF THE ELEMENTS IS: ",tfp.stats.variance(tensor).numpy())
#for variance, alternate method is
#tf.stats.reduce_variance(tf.cast(tensor,dtype = tf.float32)

THE MAX ELEMENT IS:  92.0
THE MIN ELEMENT IS:  6.0
THE SUM OF THE ELEMENTS IS:  2624.0
THE MEAN OF ALL THE ELEMENTS IS:  52.48
THE STANDARD DEVIATION OF ALL THE ELEMENTS IS:  tf.Tensor(24.712944, shape=(), dtype=float32)
THE VARIANCE OF THE ELEMENTS IS:  610.7296


### **Finding the positional maximum and minimum in the tensor**

In [51]:
min = tf.math.argmin(tensor)
max = tf.math.argmax(tensor)
tensor[max].numpy(),tensor[min].numpy()

(92.0, 6.0)

### **More mathematical operations**

In [52]:
tensor = tf.range(1,10)
tensor

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [54]:
#finding the log
tf.math.log(tensor)
#note the error

InvalidArgumentError: ignored

In [55]:
tf.math.log(tf.cast(tensor,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [56]:
#square
tf.square(tensor)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [57]:
#sqrt
tf.sqrt(tf.cast(tensor,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142137, 1.7320509, 2.       , 2.2360682, 2.4494898,
       2.6457515, 2.8284273, 3.0000002], dtype=float32)>

### **Squeezing tensors**
* squeezing tensors means to remove all the axes of dimension 1

In [58]:
tf.random.set_seed(42)
tensor = tf.random.uniform(shape=(1,1,1,50))
tensor,tensor.shape

(<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
 array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
       dtype=float32)>, TensorShape([1, 1, 1, 50]))

In [59]:
tensor = tf.squeeze(tensor)
tensor.ndim,tensor.shape

(1, TensorShape([50]))

### **One hot encoding the tensors**

In [60]:
somelist = [1,2,3,4]
tensor = tf.one_hot(somelist,4)
tensor

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

### **Exploring tensorflow's compatibility with numpy**

In [61]:
tensor = tf.constant(np.array([1.,2.,3.,4.]))
tensor

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([1., 2., 3., 4.])>

In [62]:
tensor.numpy()[0]

1.0

In [63]:
np.array(tensor),type(np.array(tensor))

(array([1., 2., 3., 4.]), numpy.ndarray)

In [64]:
tensor1 = tf.constant(np.array([1.,2.,3.,4.]))
tensor2 = tf.constant([1.,2.,3.,4.])
tensor1.dtype,tensor2.dtype
#notice the differences in the data type

(tf.float64, tf.float32)

### **Using GPUs to run our code**
* whenever out program has an access to gpu, tensorflow will automatically use it as and when needed

In [66]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [67]:
!nvidia-smi

Sat Oct  9 11:43:55 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.74       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P0    62W / 149W |    172MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------